  
//------------------------------------------------------------------------------
// <auto-generated>
//     此代码由工具生成
//     如果重新生成代码，将丢失对此文件所做的更改。
// </auto-generated>
//------------------------------------------------------------------------------
using System;
using System.Collections.Generic;
using System.Linq;
using System.Text;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;

[Table("Employee")]
public class Employee
{
	/// <summary>
	/// 主键
	/// </summary>
	public virtual int Id
	{
		get;
		set;
	}

	[StringLength(xx)]
	public virtual string Name
	{
		get;
		set;
	}

	public virtual int Age
	{
		get;
		set;
	}

	public virtual DateTime Attribute2
	{
		get;
		set;
	}

	public virtual Company Company
	{
		get;
		set;
	}

}

