  
//------------------------------------------------------------------------------
// <auto-generated>
//     此代码由工具生成
//     如果重新生成代码，将丢失对此文件所做的更改。
// </auto-generated>
//------------------------------------------------------------------------------
namespace MyPackage
{
	using System;
	using System.Collections.Generic;
	using System.Linq;
	using System.Text;
	using System.ComponentModel.DataAnnotations;
	using System.ComponentModel.DataAnnotations.Schema;

	[Table("Class1")]
	public partial class Class1
	{
		/// <summary>
		/// 名字
		/// </summary>
		[StringLength(xx)]
		[StringLength(600)]
		public virtual string Name
		{
			get;
			set;
		}

		/// <summary>
		/// 编号
		/// </summary>
		[Key]
		public virtual int ID
		{
			get;
			set;
		}

	}
}

