  
//------------------------------------------------------------------------------
// <auto-generated>
//     此代码由工具生成
//     如果重新生成代码，将丢失对此文件所做的更改。
// </auto-generated>
//------------------------------------------------------------------------------
namespace Profile
{
	using System;
	using System.Collections.Generic;
	using System.Linq;
	using System.Text;
	using AutoMapper;
	using Common;

	public partial class Class1Profile : Profile
	{
		public Class1Profile(){
			//映射关系配置
			CreateMap<Class1,Class1View>();
		}
	}
}

