// ------------------------------------------------------------------------------
// <auto-generated>
//     此代码由工具生成。
//     运行时版本: 14.0.0.0
//  
//     对此文件的更改可能导致不正确的行为，如果
//     重新生成代码，则所做更改将丢失。
// </auto-generated>
// ------------------------------------------------------------------------------
namespace T4_test
{
    using System.Linq;
    using System.Text;
    using System.Collections.Generic;
    using System;
    
    /// <summary>
    /// Class to produce the template output
    /// </summary>
    
    #line 1 "C:\Users\cbyi\Source\Repos\CsharpTest\ConsoleApplication1\T4_test\C06RTTemplateSon.tt"
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.TextTemplating", "14.0.0.0")]
    public partial class C06RTTemplateSon : C06RTTemplateFather
    {
#line hidden
        /// <summary>
        /// Create the template output
        /// </summary>
        public override string TransformText()
        {
            this.Write("\r\n");
            
            #line 7 "C:\Users\cbyi\Source\Repos\CsharpTest\ConsoleApplication1\T4_test\C06RTTemplateSon.tt"
   
  // Set the base template properties:  
  base.Description = "Description for this C06RTTemplateSon class";   
  
  // Run the base template:  
  base.TransformText();  
  

            
            #line default
            #line hidden
            this.Write("  \r\nEnd material for DerivedTemplate1.  \r\n  \r\n");
            return this.GenerationEnvironment.ToString();
        }
        
        #line 17 "C:\Users\cbyi\Source\Repos\CsharpTest\ConsoleApplication1\T4_test\C06RTTemplateSon.tt"
  
// Provide a fragment specific to this derived template:  
  
protected override void SpecificFragment(int n)  
{  

        
        #line default
        #line hidden
        
        #line 22 "C:\Users\cbyi\Source\Repos\CsharpTest\ConsoleApplication1\T4_test\C06RTTemplateSon.tt"
this.Write("  \r\n   Specific to DerivedTemplate1 : ");

        
        #line default
        #line hidden
        
        #line 23 "C:\Users\cbyi\Source\Repos\CsharpTest\ConsoleApplication1\T4_test\C06RTTemplateSon.tt"
this.Write(this.ToStringHelper.ToStringWithCulture(n));

        
        #line default
        #line hidden
        
        #line 23 "C:\Users\cbyi\Source\Repos\CsharpTest\ConsoleApplication1\T4_test\C06RTTemplateSon.tt"
this.Write("  \r\n");

        
        #line default
        #line hidden
        
        #line 24 "C:\Users\cbyi\Source\Repos\CsharpTest\ConsoleApplication1\T4_test\C06RTTemplateSon.tt"
  
}  

        
        #line default
        #line hidden
    }
    
    #line default
    #line hidden
}
