  
//------------------------------------------------------------------------------
// <auto-generated>
//     此代码由工具生成
//     如果重新生成代码，将丢失对此文件所做的更改。
// </auto-generated>
//------------------------------------------------------------------------------
namespace MyPackage
{
	using System;
	using System.Collections.Generic;
	using System.Linq;
	using System.Text;
	using System.ComponentModel;
	using System.ComponentModel.DataAnnotations;
	using System.ComponentModel.DataAnnotations.Schema;

	public partial class Class1View
	{
		/// <summary>
		/// 名字
		/// </summary>
		[DisplayName("名字")]
		[StringLength(xx, ErrorMessage = "名字不能超过xx个字")]
		[StringLength(600)]
		public virtual string Name
		{
			get;
			set;
		}

		/// <summary>
		/// 编号
		/// </summary>
		[DisplayName("编号")]
		public virtual int ID
		{
			get;
			set;
		}

	}
}

