  
//------------------------------------------------------------------------------
// <auto-generated>
//     此代码由工具生成
//     如果重新生成代码，将丢失对此文件所做的更改。
// </auto-generated>
//------------------------------------------------------------------------------
using System;
using System.Collections.Generic;
using System.Linq;
using System.Text;
using System.ComponentModel;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;

public class EmployeeView
{
	/// <summary>
	/// 主键
	/// </summary>
	[DisplayName("主键")]
	public virtual int Id
	{
		get;
		set;
	}

	[DisplayName("")]
	[StringLength(xx, ErrorMessage = "不能超过xx个字")]
	public virtual string Name
	{
		get;
		set;
	}

	[DisplayName("")]
	public virtual int Age
	{
		get;
		set;
	}

	[DisplayName("")]
	public virtual DateTime Attribute2
	{
		get;
		set;
	}

	public virtual Company Company
	{
		get;
		set;
	}

}

